language: rust
cache: cargo
dist: trusty
os:
  - linux
  - osx

# run builds ffor all the supported trains
rust:
  - nightly
  - beta
  - stable
  - 1.0.0

# the main script
script:
  - cargo build
  - cargo test